language: java
#jdk:
#  - oraclejdk8
#  - openjdk8
#stages:
  # - Tests
  # - Tests2
  # - name: Test3
   # if: branch = master
jobs:
   include:
    - name: "test1"
      script: 
        - mvn -e install verify 
        - echo "Running unit tests (1)"
    - script: 
        - bash abc.sh
        - echo "Running unit tests (2)"
      name: "test2"
    - stage: "Tests1"
      name: "Test3"
      dist: xenial
      script: bash script2.sh



