language: java
jdk:
  - oraclejdk8
  - oraclejdk11
 
#git:
  #depth: 1
  #quiet: true
# Skip the default mvn command because we want to set the profile explicitly
install: true
script:
  - mvn -e install verify 
addons:
  apt:
    packages:
      - oracle-java8-installer
