language: java
jdk:
  - oraclejdk8
  - openjdk8
jobs:
   include:
    - stage: "Tests"
      name: "Test1"
      script: mvn -e install verify 
    - script: bash abc.sh 
    - stage: "Tests"
      name: "Test2"
      script: bash script2.sh



