language: java
jdk:
  - oraclejdk8
  - openjdk8
 jobs:
   include:
    - stage: "Tests"
      name: "Test1"
      script: mvn -e install verify 
    - script: bash abc.sh 
    - stage: "Tests"
      name: "Test2"
      script: bash script2.sh



<<<<<<< HEAD
=======
install: 
- true
- echo " hello " 
script:
  - mvn -e install verify 
  - bash abc.sh
#addons:
  #chrome: stable
>>>>>>> 14dba4ff65c3fee7feefc8740bbd051a7ac09732
