language: java
jdk:
  - oraclejdk8
  - oraclejdk9
#git:
  #depth: 1
  #quiet: true

# Skip the default mvn command because we want to set the profile explicitly
install: true
script:
  - mvn -e install verify 
before_script:
 matrix:
  include:
    - jdk: oraclejdk8
  exclude:
    - jdk: oraclejdk9


