language: java
jdk:
  #- oraclejdk8
  - openjdk8
 
#git:
  #depth: 1
  #quiet: true
# Skip the default mvn command because we want to set the profile explicitly


install: 
- true
- echo " hello " 
script:
  - mvn -e install verify 
  - ./abc.sh
#addons:
  #chrome: stable
